language: java
branches:
  only:
  - master
  - coverity_scan
jdk: openjdk17
env:
  global:
    secure: zPlOGh+E23GojWKguc896WzUkhKlM0vr6mPTOPCsPLRgx7LctZ2w5KGNKs6d3vxGyfFoNEyThnzNsivd7GI9NtfQT2R/exQTK5m0qPzN+Oj21WNsw4CScrZWtzGNmfLYUEXtoeyKVoWsEWYtFb29OeKLipBoZFckkYcVMKMjhIUZ2CXprjRROeb34RGuPHs7pOaFBst0RLeJLGWrYa8rvimdzP+2x3KvJqR77bTGO2DXIms8QsokQVh8bGFEPMtFPOx3tnXyeWz8/GOsn5YZnXDWQI8q7hEnzpjs9W1vVQeVhEt9apkXl+86FwIw3gyznIdWZeA3omRg5A+nNRcWAn8jU6ypo9KmL9FwphWruo1g3y8YICZ//i2f/JmxdZQFPgY8D50vU28scgvBxx7k6vBJplokO9U2Nasb6PyAl7hkvnubSjXNkR5qAIj0Axoqq6irpB/ODFicGamkI95ZWzNjBnfNffwtr4nH5IF6e7xRS9OvWyDAvDBiEPwFPAn96baJk6QqNbJ7OFrQ2ZGpBIYc/JLx2ndQdW4MbVB6VVifJpUJny4BqBvA8IZXQEm7NdpPF9FAx4YfAdLho6ykAZ4z9I+x1XiDuZzYXJr34L0xZqzqEAfr3tL1ekJCNJDoIZrEgfhhwvE0iZ7db7wZkuKix833yI/bdpk2E8YYI8I=

addons:
  coverity_scan:

    project:
      name: slug-kit/BakeNow
      version: 0.1
      description: Bake! Now!!!

    notification_email: SeraphUltimateX@gmail.com

    build_command_prepend: mvn clean

    build_command: mvn package

    branch_pattern: coverity_scan